[providers]
python = "3.11"

[phases.setup]
dependsOn = ["..."]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"] 
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT devops.wsgi:application"