# Generated by Django 4.2.24 on 2025-09-22 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='calltype',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('fov', 'Field Visit'), ('teams', 'Teams'), ('other', 'Other')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='vibe',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
