# Generated by Django 4.2.24 on 2025-09-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.employee'),
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.owner'),
        ),
        migrations.AlterField(
            model_name='report',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.office'),
        ),
    ]
