# Generated by Django 4.2.24 on 2025-09-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_employee_email_employee_potential'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='transcript',
            field=models.BooleanField(default=False),
        ),
    ]
