# Generated by Django 4.2.24 on 2025-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_report_subject_report_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='last_contacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='last_contacted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
