# Generated by Django 4.2.24 on 2025-11-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0008_office_last_contacted_owner_last_contacted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['name'], 'verbose_name': 'Office Space', 'verbose_name_plural': 'Office Spaces'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Communication Report', 'verbose_name_plural': 'Communication Reports'},
        ),
        migrations.AddField(
            model_name='office',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='All owners of this office (can select multiple)', related_name='offices', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='office',
            name='primary_owner',
            field=models.ForeignKey(blank=True, help_text='Main owner who serves as primary contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_offices', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='report',
            name='additional_owners',
            field=models.ManyToManyField(blank=True, help_text='Additional owners involved in this communication', related_name='secondary_reports', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='report',
            name='primary_owner',
            field=models.ForeignKey(blank=True, help_text='Main owner contact for this communication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_reports', to='owners.owner'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use office.primary_owner or office.owners instead', null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.owner'),
        ),
        migrations.AlterField(
            model_name='office',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Single owner (being migrated to multi-owner support)', null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.owner'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.employee'),
        ),
        migrations.AlterField(
            model_name='report',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.office'),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Single owner (being migrated to primary_owner)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_reports', to='owners.owner'),
        ),
    ]
