# Generated by Django 4.2.24 on 2025-11-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0009_alter_employee_options_alter_office_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='owners.office'),
        ),
    ]
